# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/xmldom-decorators" # Location of package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/xmldom-decorators-cli" # Location of package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/xmldom-decorators-test" # Location of package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/sample-clients" # Location of package.json
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
