name: Tests

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test
    - name: archive xmldom-decorators
      uses: actions/upload-artifact@v3
      with:
        name: xmldom-decorators.tgz
        path: artifacts/build/xmldom-decorators.tgz
    - name: archive xmldom-decorators-cli
      uses: actions/upload-artifact@v3
      with:
        name: xmldom-decorators-cli.tgz
        path: artifacts/build/xmldom-decorators-cli.tgz
